language: java
jdk:
  - openjdk8

branches:
  only:
    - develop

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: letshadow-s3-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: private                         # 현재 public access가 차단된 상태
    wait-until-deployed: true
    on:
      repo: bgpark82/nearlog
      branch: develop

notifications:
  email:
    recipients:
      - bgpark82@gmail.com