spring:
  profiles:
    active: local

jwt.secret: test
jwt.expiration: 30

cloud.aws.s3.bucket: nearlog
cloud.aws.region.static: ap-northeast-2
cloud.aws.stack.auto: false

spring.servlet.multipart.max-file-size: 50MB
spring.servlet.multipart.max-request-size: 50MB

---
spring.profiles: local
spring.profiles.include: aws

# h2 설정
spring.h2.console.enabled: true
spring.h2.console.settings.web-allow-others: true
spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

# h2 로그 설정
logging.level.org.hibernate.SQL: debug            # 로그 형식으로 쿼리 보여주기
spring.jpa.properties.hibernate.format_sql: true  # 압축된 쿼리를 읽기 좋게 포멧
spring.jpa.hibernate.ddl-auto: create             # 서버 시작에 테이블 생성



---
spring.profiles: dev
spring.profiles.include: db

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# s3 iam role 사용
cloud.aws.credentials.instanceProfile: true
